"""MIGRATION

Revision ID: 00a52af17484
Revises: 302bb4f663bf
Create Date: 2026-02-18 10:05:05.480342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a52af17484'
down_revision: Union[str, Sequence[str], None] = '302bb4f663bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_cart_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('contacts_reply_to_fkey'), 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('contacts_sender_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('contacts_recipient_id_fkey'), 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contacts', 'contacts', ['reply_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'contacts', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('orders_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_buyer_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('products_seller_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('products_seller_id_fkey'), 'products', 'users', ['seller_id'], ['id'])
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_buyer_id_fkey'), 'orders', 'users', ['buyer_id'], ['id'])
    op.create_foreign_key(op.f('orders_address_id_fkey'), 'orders', 'addresses', ['address_id'], ['id'])
    op.alter_column('orders', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(op.f('contacts_recipient_id_fkey'), 'contacts', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(op.f('contacts_sender_id_fkey'), 'contacts', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('contacts_reply_to_fkey'), 'contacts', 'contacts', ['reply_to'], ['id'])
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_user_id_fkey'), 'carts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_cart_id_fkey'), 'cart_items', 'carts', ['cart_id'], ['id'])
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_user_id_fkey'), 'addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
