"""MIGRATION

Revision ID: 45676802eb87
Revises: 6caaf7c8aefc
Create Date: 2026-03-01 12:47:32.294534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45676802eb87'
down_revision: Union[str, Sequence[str], None] = '6caaf7c8aefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('max_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'max_price')
    # ### end Alembic commands ###
