"""MIGRATION

Revision ID: 6ab17e6ad3d9
Revises: 632cb3793016
Create Date: 2026-02-27 11:17:42.759029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab17e6ad3d9'
down_revision: Union[str, Sequence[str], None] = '632cb3793016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=False),
    sa.Column('cta_href', sa.String(length=300), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_banners_id'), 'hero_banners', ['id'], unique=False)
    op.create_index(op.f('ix_hero_banners_is_active'), 'hero_banners', ['is_active'], unique=False)
    op.create_index(op.f('ix_hero_banners_sort_order'), 'hero_banners', ['sort_order'], unique=False)
    op.create_table('hero_banner_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['hero_banners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_banner_images_banner_id'), 'hero_banner_images', ['banner_id'], unique=False)
    op.create_index(op.f('ix_hero_banner_images_id'), 'hero_banner_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hero_banner_images_id'), table_name='hero_banner_images')
    op.drop_index(op.f('ix_hero_banner_images_banner_id'), table_name='hero_banner_images')
    op.drop_table('hero_banner_images')
    op.drop_index(op.f('ix_hero_banners_sort_order'), table_name='hero_banners')
    op.drop_index(op.f('ix_hero_banners_is_active'), table_name='hero_banners')
    op.drop_index(op.f('ix_hero_banners_id'), table_name='hero_banners')
    op.drop_table('hero_banners')
    # ### end Alembic commands ###
