"""MIGRATION

Revision ID: 6caaf7c8aefc
Revises: f74ea95f8fb4
Create Date: 2026-02-27 18:44:18.508913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6caaf7c8aefc'
down_revision: Union[str, Sequence[str], None] = 'f74ea95f8fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('phone', sa.String(length=30), nullable=True))
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_read'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_recipient_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_recipient_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_reply_to'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_sender_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_sender_user_id'), table_name='contacts')
    op.drop_column('contacts', 'subject')
    op.drop_column('contacts', 'recipient_name')
    op.drop_column('contacts', 'sender_name')
    op.drop_column('contacts', 'recipient_phone')
    op.drop_column('contacts', 'recipient_user_id')
    op.drop_column('contacts', 'sender_email')
    op.drop_column('contacts', 'recipient_email')
    op.drop_column('contacts', 'sender_phone')
    op.drop_column('contacts', 'sender_user_id')
    op.drop_column('contacts', 'reply_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('reply_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('sender_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('sender_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('recipient_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('sender_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('recipient_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('recipient_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('sender_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('recipient_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_contacts_sender_user_id'), 'contacts', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_sender_email'), 'contacts', ['sender_email'], unique=False)
    op.create_index(op.f('ix_contacts_reply_to'), 'contacts', ['reply_to'], unique=False)
    op.create_index(op.f('ix_contacts_recipient_user_id'), 'contacts', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_recipient_email'), 'contacts', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_contacts_is_read'), 'contacts', ['is_read'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.drop_column('contacts', 'phone')
    op.drop_column('contacts', 'email')
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###
