"""MIGRATION

Revision ID: ccfafd57b39f
Revises: 48c763a3167d
Create Date: 2026-02-18 09:13:09.935598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccfafd57b39f'
down_revision: Union[str, Sequence[str], None] = '48c763a3167d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.alter_column('carts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('carts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contacts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('order_items', sa.Column('product_name', sa.String(length=200), nullable=False))
    op.add_column('order_items', sa.Column('price_at_purchase', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('shipping_fee', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'shipped', 'delivered', 'cancelled', name='order_status'),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'shipped', 'delivered', 'cancelled', name='order_status'),
               nullable=False)
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'address_id')
    op.drop_column('order_items', 'price_at_purchase')
    op.drop_column('order_items', 'product_name')
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contacts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('carts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('carts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
