"""MIGRATION

Revision ID: f74ea95f8fb4
Revises: 6ab17e6ad3d9
Create Date: 2026-02-27 18:32:39.190606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74ea95f8fb4'
down_revision: Union[str, Sequence[str], None] = '6ab17e6ad3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('sender_user_id', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('recipient_user_id', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('sender_name', sa.String(length=120), nullable=False))
    op.add_column('contacts', sa.Column('sender_email', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('sender_phone', sa.String(length=30), nullable=True))
    op.add_column('contacts', sa.Column('recipient_name', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('recipient_email', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('recipient_phone', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_is_read'), 'contacts', ['is_read'], unique=False)
    op.create_index(op.f('ix_contacts_recipient_email'), 'contacts', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_contacts_recipient_user_id'), 'contacts', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_reply_to'), 'contacts', ['reply_to'], unique=False)
    op.create_index(op.f('ix_contacts_sender_email'), 'contacts', ['sender_email'], unique=False)
    op.create_index(op.f('ix_contacts_sender_user_id'), 'contacts', ['sender_user_id'], unique=False)
    op.drop_constraint(op.f('contacts_sender_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('contacts_recipient_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('contacts_reply_to_fkey'), 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'recipient_id')
    op.drop_column('contacts', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('contacts_reply_to_fkey'), 'contacts', 'contacts', ['reply_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('contacts_recipient_id_fkey'), 'contacts', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('contacts_sender_id_fkey'), 'contacts', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contacts_sender_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_sender_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_reply_to'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_recipient_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_recipient_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_read'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_column('contacts', 'recipient_phone')
    op.drop_column('contacts', 'recipient_email')
    op.drop_column('contacts', 'recipient_name')
    op.drop_column('contacts', 'sender_phone')
    op.drop_column('contacts', 'sender_email')
    op.drop_column('contacts', 'sender_name')
    op.drop_column('contacts', 'recipient_user_id')
    op.drop_column('contacts', 'sender_user_id')
    # ### end Alembic commands ###
